---
# defaults file for rhsso
rhsso_repos:
  - "jb-eap-7.4-for-rhel-8-x86_64-rpms"
  - "rh-sso-7.6-for-rhel-8-x86_64-rpms"
rhsso_admin_user: "admin"
rhsso_admin_password: "changeme"
rhsso_ssl_password: "changeme"
rhsso_ssl_path: "{{ ansible_env['HOME'] | default ('/var/tmp/') }}"
rhsso_ssl_type: "pkcs12"
rhsso_bind_ip: "0.0.0.0"
